version: '3.8'

services:
  graphite:
    container_name: graphite
    image: graphiteapp/graphite-statsd:latest
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    restart: always
